### ISSUE TITLE
[Bug]: Group does not respect initProvider values

### ISSUE THREAD

**Issue by Mikel-Landa** [crossplane-contrib/provider-upjet-azuread#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* groups.azuread.upbound.io/v1beta2 - Group

### Resource MRs required to reproduce the bug

```yaml
apiVersion: groups.azuread.upbound.io/v1beta2
kind: Group
metadata:
  name: test
 spec:
  deletionPolicy: Delete
  forProvider:
    displayName: Test
    securityEnabled: true
  initProvider:
    owners:
      - <uuid>
    members: []
 ```

### Steps to Reproduce

Create the group. Add users manually in Azure portal to either owner or members fields.

### What happened?

 If members is an empty array, it won't persist as a field in initProviders, which is not expected behaviour.

Also, even if we populate the array of members/owners, crossplane will eventually delete external users from the group

### Relevant Error Output Snippet

```shell
No error, but in the Activity log tab of the group, a delete operation is shown with User-Agent:

HashiCorp Terraform/ (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azuread/dev Hamilton (Go-http-client/1.1) pid-222c6c49-1b0a-5959-a213-6608f9eb8820
```

### Crossplane Version

1.16.0

### Provider Version

1.3.0

### Kubernetes Version

1.28.9

### Kubernetes Distribution

AKS
