### ISSUE TITLE
[Bug]: cannot convert from the spoke version "v1beta1" to the hub version "v1beta2"

### ISSUE THREAD

**Issue by jorgelon** [crossplane-contrib/provider-upjet-azuread#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

applications.azuread.upbound.io/v1beta1 updating from provider-azuread v1.1.0 to v1.2.0 or v1.4.1

### Resource MRs required to reproduce the bug

I do not know what application(s) give me that error but this is an example

```yaml
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  name: myappp
spec:
  forProvider:
    displayName: "whatever"
    web:
      - redirectUris:
          - "https://XXXX"
          - "https://YYYY"
      - homepageUrl: "ZZZZZZZZ"
```

### Steps to Reproduce

run a 
`kubectl get applications.applications.azuread.upbound.io`

### What happened?

I cannot get the applications

### Relevant Error Output Snippet

```shell
Error from server: conversion webhook for applications.azuread.upbound.io/v1beta1, Kind=Application failed: cannot convert from the spoke version "v1beta1" to the hub version "v1beta2": cannot apply the PavedConversion for the "azuread_application" object: failed to convert the source map in mode "toEmbeddedObject" with source API version "v1beta1", target API version "v1beta2": singleton list, at the field path optionalClaims, must have a length of at most 1 but it has a length of 3
```

### Crossplane Version

1.14, 1.15 and 1.16

### Provider Version

v1.2.0 or v1.4.1

### Kubernetes Version

1.29

### Kubernetes Distribution

kubeadm
