### ISSUE TITLE
[Bug]: The update of existing Azure AD app doesn't work

### ISSUE THREAD

**Issue by eriksML** [crossplane-contrib/provider-upjet-azuread#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

applications.azuread.upbound.io/v1beta1 - Application

### Resource MRs required to reproduce the bug

```
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  name: my-app-test
  annotations:
    crossplane.io/external-name: "/applications/00000000-0000-0000-0000-000000000000"
spec:
  managementPolicies: ["Observe"]
  forProvider:
    displayName: my-app-test
    identifierUris:
    - "dummyurl.com"
  providerConfigRef:
    name: azuread-provider-config
```

### Steps to Reproduce

- updating the existing Azure AD application

### What happened?

Hi crossplane team,

we need to update the existing azure AD application by adding redirect uris for SSO configuration.
However looks it's not working with the azuread provider the version 1.6.0.

### Relevant Error Output Snippet

```shell
Warning CannotObserveExternalResource 33s managed/applications.azuread.upbound.io/v1beta1, kind=application external resource does not exist
```

### Crossplane Version

1.18.0

### Provider Version

1.6.0

### Kubernetes Version

v1.31.0

### Kubernetes Distribution

minikube

### Additional Info

I've tried to use identifierUris as an additional field but still not working. Changing the management policy and using "*" creates a new app instead of updating the existing one. My provider config has ReadWrite permissions for all apps.

**Comment by mergenci** [comment]
Thanks for your report @eriksML. To clarify, you're interested in _importing_ a resource [as documented here](https://docs.crossplane.io/latest/guides/import-existing-resources/), right?

**Comment by eriksML** [comment]
Hi @mergenci, yes you're right.

**Comment by turkenf** [comment]
Hi @eriksML, 

I could not reproduce the issue on my side. Please make sure you have given the correct value to the `crossplane.io/external-name` annotation. It should be: `crossplane.io/external-name: /applications/<Object ID>`

**Comment by eriksML** [comment]
Hi @turkenf,

thank you for your response. Could you send your application manifest please?
Are you using 
`managementPolicies: ["Observe"]`
for importing the resource firstly?
My manifest is in the description where I have the correct value in the name annotation.
I've tested it again with the latest provider version and still getting the error

_Warning  CannotObserveExternalResource  99s (x3 over 6m56s)  managed/applications.azuread.upbound.io/v1beta1, kind=application  external resource does not exist_

**Comment by turkenf** [comment]
Hi @eriksML,

> thank you for your response. Could you send your application manifest please?
Are you using
managementPolicies: ["Observe"]

Yes, and the YAML file:

```
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    crossplane.io/external-name: /applications/dab15385-60c1-45ca-837e-66050aaa5555
  name: test-import
spec:
  managementPolicies: ["Observe"]
  forProvider:
    displayName: example-test-import
```
